name: Release Creation Action
on:
  pull_request:
    types: [labeled, milestoned]
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:22
    if: contains(gitea.event.pull_request.labels.*.name, 'Project/Release')
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Print full event payload
        run: |
          echo "Event Payload:"
          echo "${{ toJson(gitea) }}"          
#      - uses: https://git.vistta.org/vistta/template@package-update-beta
#        with:
#          version: '${{ gitea.event.pull_request.milestone.title }}'