name: Release Creation Action
on:
  pull_request:
    types: [labeled, milestoned]
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:22
    if: contains(github.event.pull_request.labels.*.name, 'Project/Release')
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Print full event payload
        run: |
          version="${{ gitea.event.pull_request.milestone.title }}"
          package_version=$(jq -r '.version' package.json)
          echo "Release: $version over $package_version"