name: Release Creation Action
on:
  pull_request:
    types: [labeled]
    branches:    
      - master
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:22
    if: ${{ github.event.pull_request.labels[0].name == 'Project/Release*' && github.event.pull_request.milestone == null }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ gitea.event.pull_request.head.ref }}

      - name: Template
        run: |
          echo "${{ github.event.pull_request.labels }}"
#      - uses: actions/checkout@v4
#        with:
#          repository: vistta/actions
#          ref: master
#          token: ${{ secrets.GIT_TOKEN }}
#          path: "./.gitea/actions"

#      - name: "Start Release"
#        uses: ./.gitea/actions/start-release
#        with:
#          version: '${{ gitea.event.pull_request.milestone.title }}'
#          ref: ${{ gitea.event.pull_request.head.ref }}