name: Release Start Action
on:
  pull_request:
    types: [labeled]
    branches:    
      - master
jobs:
  Release:
    runs-on: ubuntu-latest
    container:
      image: node:22
    if: ${{ startsWith(gitea.event.pull_request.labels[0].name, 'Project/Release') && gitea.event.pull_request.milestone == null }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ gitea.event.pull_request.head.ref }}

      - name: "Setup Actions"
        uses: actions/checkout@v4
        with:
          repository: vistta/actions
          ref: master
          token: ${{ secrets.GIT_TOKEN }}
          path: "./.gitea/actions"

      - name: "Start Release"
        uses: ./.gitea/actions/start-release
        with:
          type: '${{ gitea.event.pull_request.labels[0].name }}'
          token: ${{ secrets.GIT_TOKEN }}