name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  Validation:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      -
        name: Setup Env
        uses: actions/checkout@v4
        with:
          repository: vistta/vistta
          ref: ${{ gitea.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_TOKEN }}
      - 
        name: Debug
        run: |
          git config user.email "devops@vistta.org"
          git config user.name "devops"
      - 
        name: Setup Node
        run: npm ci
      - 
        name: Checkout
        uses: ./.gitea/actions/checkout
      - 
        name: Validations
        run: |
          echo "Validations"
      - 
        name: Unit Tests
        run: |
          npm run test