name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  Validation:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Print full event payload
        run: |
          echo "${{ toJson(github.event) }}"
#    if: ${{ startsWith(gitea.event.pull_request.labels[0].name, 'Project/Release') && gitea.event.pull_request.milestone == null }}