name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  Validation:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - 
        name: "Checkout"
        uses: actions/checkout@v4
      - 
        name: NPM Setup
        run: npm ci
      - 
        name: Validations
        run: |
          echo "Validations"
      - 
        name: Unit Tests
        run: |
          echo "Unit Tests"