name: Project Validation
on:
  pull_request:
    types: [synchronize]
    branches:    
      - master
jobs:
  Setup:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: vistta/vistta
          ref: ${{ gitea.event.pull_request.head.ref }}
          token: ${{ secrets.GIT_TOKEN }}
          fetch-depth: 0
          submodules: true